# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.5.1
_src_path: gh:algorandfoundation/algokit-fullstack-template
author_email: your@email.tld
author_name: Your-Name
contract_name: hello_world
deployment_language: typescript
ide_vscode: true
preset_name: starter
project_name: pyteal-beaker-template
use_python_black: true
use_python_pytest: false

